### ISSUE TITLE
Is this as fast as latest LM Studio updates?

### ISSUE THREAD

**Issue by shiloh92** [Rivridis/LLM-Assistant#5]
Silly question. I am hoping to use this for a simple chat ux locally that would not need LM Studio. I just want to make sure the parameters passed to the mistral or llama models include the updates to Llama and everything else that might result in faster inference. 
Thank you for sharing your assistant base!

**Comment by Rivridis** [comment]
Yup, I just copied the parameters from LM Studio, and tried my best to tweak it to make it as fast as possible.
According to my tests, llama-cpp-python runs just as fast as LM studio. 
I do need to enable token streaming to view responses in real time, but I have no idea how to do that with Gradio.
